version: '3.8'

services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - '5432'
  wallet-service:
    container_name: wallet-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DB_PORT: 5432
      DB_HOST: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
